export const txt = [
        "pip install 77",
        "Requirement-already-satisfied:-77-in-y:/users/you/data/mind/programs/mood/mood1day/packagesV1.4",
        "pip install hate",
        "ERROR: Could not find a version that satisfies the requirement hate (from versions: none)",
        "ERROR: No matching distribution found for hate",
        "Initializing-Love",
        "Done.",
        "Loading Interface...",
        "Collecting Data...",
        "Decrypting Data...",
        "Securing Connection...",
        "Connecting...",
        "Initializing-goodmood",
        "Done.",
        "Loading Interface...",
        "Collecting Data...",
        "Decrypting Data...",
        "Securing Connection...",
        "Connecting...",
        "Initializing Server..",
        "Authenticating..",
        "Obtaining Keypass..",
        "Connect ion Successful.",
        "Redirecting...",
        "안녕하세요. 무엇을 작성해야 할지 모르겠습니다. 실제로는 내 코드에 미적 감각을 더하기 위해 한국어로 작성된 텍스트가 필요합니다. 비주얼은 나쁘지 않고 마음에 듭니다. 이 텍스트를 번역하는 것이 귀찮다면 메시지를 보내주세요. 커피를 사드리겠습니다!",
        "안녕하세요. 무엇을 작성해야 할지 모르겠습니다. 실제로는 내 코드에 미적 감각을 더하기 위해 한국어로 작성된 텍스트가 필요합니다. 비주얼은 나쁘지 않고 마음에 듭니다. 이 텍스트를 번역하는 것이 귀찮다면 메시지를 보내주세요. 커피를 사드리겠습니다!",
        "|",     
        "Server Diagnostics:",
        "IP: 198.162.0.7:2222",
        "Gateway: 225.225.225 0 Flags up",
        "ServerAddress: 196.283.84.72",
        "ServerNewAddress: 175.297.64.75",
        "ServerFakeAddress: 283.223.29.91",
        "MyNewPhoneNumber: 532-paf-pasteque",
        "Username: User7_Fc4234-msHC333Z4",
        "Password: lifeisbeautiful=8-90°",
        "$(function(){\n\t$.database.get('Password')\n});",
        "exec({\n\t'Password' : 'KbJ7zpQ',\n\t'Username' : 'Administrator'\n});",
        ">>> Command Returned 2",
        ">>> Return 0;",
        "## Server Connected",
        "## Server Disconnected",
        "## Connection Refused",
        "ACCESS DENIED",
        "ACCESS GRANTED",
        "Password: ********\n>>> Incorrect Password\n## Server Disconnected",
        "\n\nNMAP\n\n\tIP: 198.162.0.24\n\tPlatform: Linux armv7\n\tUsers Connected: 27\n\tNetmask: 255.255.255.0\n\t0 flags up\n\n\t",
        "Reconnecting...",
        ">>> 'Leave a like!\n\tBy: Andrew Grider'",
        "/bin ~ # sudo chown /system/",
        "$.system.on();\n\t[SYSTEM]:Antivirus Protocol Overridden\n\t[SERVER]:Firewall Disabled\n\t",
        "[ROOT]:Filesystem Formatted",
        "oauth: ks7bJpp8bvxz35hq"
    ]
